### ISSUE TITLE
Meta issue: get C# test rules working

### ISSUE THREAD

**Issue by j3parker** [Brightspace/rules_csharp#128]
(This is an issue rather than a milestone because issues can only be in one milestone and I like the current organization of our milestones).

We want `csharp_nunit_test` to work, and possibly a general `csharp_test` rule (with `csharp_nunit_test` as a macro for that).

The current state is that it works but all of your deps need to be in the same directory because of assembly resolution. There are also platform hiccups to be solved.

Mandatory issues (I've got some WIP fixes for these; they're tightly coupled):
- [ ] #9: bazel run/bazel test only work in specific circumstances
- [ ] #71: bazel run doesn't work for .NET Core on Linux and MacOS

Optional:
- [ ] #51 Add a generic csharp_test built on top of vstest

Related:
- [ ] #45 The CLR fails sporadically in the Linux sandbox, likely due to a race condition in /tmp

**Comment by j3parker** [comment]
See the comment in this example:

https://github.com/Brightspace/rules_csharp/blob/master/examples/basic/BUILD#L16-L25
